config/routes.rb
Rails.application.routes.draw do
 
 root 'static_pages#home'
 
  get '/home' => 'static_pages#home'
  
  get '/help' => 'static_pages#help'
  
  get '/about' => 'static_pages#about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | Building and App With Liam </title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <header class="headSec">
     <h1>Golf Store</h>
     <ul>
       <li><%= link_to "Home", "/" %></li>
       <li><%= link_to "About", about_path %></li>
       <li><%= link_to "Help", help_path %></li>
     </ul>
   </header>
   <div class="container">
    <%= yield %>
    </div>
    <footer class="foot">
        <h1>I'm the Footer</h1>
    </footer>
  </body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<p>test branch</p>
<h1>About My App</h1>
<p>This could possibly be the best application ever made.....maybe!</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>

<h1>AGGGGGHHHHH Help</h1>
<p>I dont know what else to do and I seem to have found my way here</p>

app/views/static_pages/home.html.erb
<% provide(:title, "Home")%>


<h1>Home</h1>
<p>Welcome to your first home page!</p> 
    <br>
    <br>
   <p>This will be the home page of Golf store</p>
</div>